name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v2
        with:
          version: 10
      - uses: actions/setup-node@v5
        with:
          node-version: 20.x
          cache: pnpm

      - run: pnpm install --shamefully-hoist=true --frozen-lockfile
      - run: pnpm run lint && pnpm run build
